import EOC.SuperBudgetCancellation

/-!
# The height of a divisibility relation, and what an external theorem must supply

Companion to `docs/INTRINSIC_EXTRINSIC_CONSTRAINT_INDEPENDENCE_AUDIT.md`.

Every exact-realizer condition in this program has the same shape: for a valuation word `D` of
length `N` with total valuation `S_N`, a candidate representative `χ` realizes `D` iff

```
2^{S_N}  divides  A + χ·Λ
```

for integers `A, Λ` **generated by the word**. Two instances:

* generic word — `A = C_N = Σ_{i<N}3^{N−1−i}2^{S_i}`, `Λ = 3^N`;
* purely periodic word of period `p` — `A = c₀`, `Λ = Δ = 3^p − 2^σ`, both independent of `N`
  (`EOC.SuperBudget.geom_closed_form`).

The only general tool converting such a divisibility into a *size* statement is the universal
integer fact behind `EOC.SuperBudget.periodic_floor`: a nonzero multiple of `2^m` has absolute
value at least `2^m`. This file records the exact consequence, which is that the strength of the
resulting floor is governed entirely by the **height** `H = max(|A|, |Λ|)` of the relation:

* `floor_of_height` — `2^m ≤ H·(1 + |χ|)`, so `|χ| ≳ 2^m/H`.
* `floor_of_height_separation` — **the theorem that isolates the missing input.** If the height is
  separated from the divisor by a factor `2^k`, i.e. `H·2^k ≤ 2^m`, then `2^k − 1 ≤ |χ|`. Taking
  `m = S_N` and `k = ⌈εN⌉` this *is* Open Problem C. So an external theorem is useful here exactly
  when it supplies a word-generated relation of height `≤ 2^{S_N − εN}`.
* `height_separation_vacuous_of_confined` — and the height actually available for an irregular
  word is not separated at all: under zero confinement `2^{S_N} ≤ 3^N`, so with `Λ = 3^N` no `k ≥ 1`
  works. The generic relation gives nothing, as a theorem rather than as an observation.
* `natLog_two_pow_mul` — the two-norm identity `log₂(2^S·m) = S + log₂ m`. Since the audit shows
  `B_N = 2^{S_N}·m_N` exactly with `m_N` the terminal iterate, the Archimedean and 2-adic readings
  of `B_N` are related by an **exact identity**, not by independence.

No `sorry`, `admit`, `axiom`, or `opaque`.
-/

namespace EOC
namespace ConstraintHeight

/-! ## 1. The two norms of `B_N` are linked by an identity -/

/-- `log₂(2^S · m) = S + log₂ m`. With `B_N = 2^{S_N}·m_N` (the audit's Gate 8 identity, `m_N`
the terminal accelerated iterate, odd and positive) this says

```
log₂|B_N| − v₂(B_N) = log₂ m_N
```

exactly. The Archimedean size of `B_N` and its 2-adic valuation are therefore a *complementary
pair joined by an exact identity*, not two independent directions: knowing one and the word
determines the other. -/
theorem natLog_two_pow_mul (S m : ℕ) (hm : 0 < m) :
    Nat.log 2 (2 ^ S * m) = S + Nat.log 2 m := by
  induction S with
  | zero => simp
  | succ S ih =>
      have hpos : 0 < 2 ^ S * m := by positivity
      have heq : (2 : ℕ) ^ (S + 1) * m = (2 ^ S * m) * 2 := by ring
      rw [heq, Nat.log_mul_base (by norm_num) hpos.ne', ih]
      omega

/-! ## 2. The height of a divisibility relation controls the floor it yields -/

/-- **The height inequality.** If `2^m` divides the nonzero integer `A + χ·Λ` and both `A` and `Λ`
have absolute value at most `H`, then

```
2^m ≤ H · (1 + |χ|).
```

Everything the "nonzero multiple of `2^m` is large" argument can deliver is contained here: the
floor on `|χ|` is `2^m/H − 1`, and it is useful exactly to the extent that `H` is small compared
with `2^m`. -/
theorem floor_of_height (A Λ χ H : ℤ) (m : ℕ)
    (hA : |A| ≤ H) (hΛ : |Λ| ≤ H)
    (hdvd : (2 : ℤ) ^ m ∣ A + χ * Λ) (hne : A + χ * Λ ≠ 0) :
    (2 : ℤ) ^ m ≤ H * (1 + |χ|) := by
  have h1 := SuperBudget.periodic_floor A Λ χ m hdvd hne
  have h2 : |χ| * |Λ| ≤ |χ| * H := by
    have : (0 : ℤ) ≤ |χ| := abs_nonneg χ
    exact mul_le_mul_of_nonneg_left hΛ this
  nlinarith [h1, h2, hA]

/-- **The theorem that isolates the missing external input.**

Suppose the word supplies a divisibility relation `2^m ∣ A + χ·Λ` whose height `H` is separated
from the divisor by a factor `2^k`, meaning `H·2^k ≤ 2^m`. Then

```
2^k − 1 ≤ |χ|.
```

With `m = S_N` and `k = ⌈εN⌉` this is exactly the exponential realizer floor of Open Problem C.
So the precise shape of what an external theorem would have to prove is: *every* zero-confined
word of length `N` admits a word-generated relation of height at most `2^{S_N − εN}`.

The hypothesis is stated abstractly on purpose — no Collatz structure is used — so that it names
the missing input without disguising it as progress. -/
theorem floor_of_height_separation (A Λ χ H : ℤ) (m k : ℕ)
    (hA : |A| ≤ H) (hΛ : |Λ| ≤ H) (hHpos : 0 < H)
    (hsep : H * 2 ^ k ≤ 2 ^ m)
    (hdvd : (2 : ℤ) ^ m ∣ A + χ * Λ) (hne : A + χ * Λ ≠ 0) :
    (2 : ℤ) ^ k - 1 ≤ |χ| := by
  have h1 := floor_of_height A Λ χ H m hA hΛ hdvd hne
  have h2 : H * 2 ^ k ≤ H * (1 + |χ|) := le_trans hsep h1
  have h3 : (2 : ℤ) ^ k ≤ 1 + |χ| := le_of_mul_le_mul_left (by linarith) hHpos
  linarith

/-! ## 3. The relation an irregular word actually supplies is not separated -/

/-- **Vacuity of the generic relation.** For an arbitrary word the only available relation is
`A = C_N`, `Λ = 3^N`, so `H ≥ 3^N`. Under zero confinement `S_N ≤ ⌊αN⌋`, hence `2^{S_N} ≤ 3^N ≤ H`,
and the separation hypothesis `H·2^k ≤ 2^{S_N}` fails for every `k ≥ 1`.

Stated as: if `2^S ≤ H` then no positive separation exponent exists. -/
theorem height_separation_vacuous_of_confined (H : ℤ) (S k : ℕ)
    (hHpos : 0 < H) (hconf : (2 : ℤ) ^ S ≤ H) (hk : 1 ≤ k) :
    ¬ (H * 2 ^ k ≤ 2 ^ S) := by
  intro hsep
  have h2 : (2 : ℤ) ^ 1 ≤ 2 ^ k := by
    exact pow_le_pow_right₀ (by norm_num) hk
  have : H * 2 ≤ H * 2 ^ k := by nlinarith
  have hS : (0 : ℤ) < 2 ^ S := by positivity
  nlinarith [hconf, hsep, this]

/-! ## 4. Positivity supplies no separation

The audit's Gate 23: positivity of the terminal iterate gives `m_N ≥ 1`, i.e. `B_N ≥ 2^{S_N}`,
i.e. `χ ≥ (2^{S_N} − C_N)/3^N`. Under confinement `2^{S_N} ≤ 3^N` and `C_N > 0`, so that bound is
strictly below `1` and therefore weaker than the already-known `χ ≥ 1`. -/

/-- **Positivity is vacuous under confinement.** If `2^S ≤ L` and `0 < A`, the positivity bound
`(2^S − A)/L` is strictly less than `1`, i.e. `2^S - A < L`. -/
theorem positivity_bound_vacuous (A L : ℤ) (S : ℕ)
    (hA : 0 < A) (hconf : (2 : ℤ) ^ S ≤ L) :
    (2 : ℤ) ^ S - A < L := by
  linarith

end ConstraintHeight
end EOC
