import EOC.Carry
import EOC.Confinement
import EOC.Realizer
import EOC.ValuationWord
import EOC.FiniteValuationWord
import EOC.CompositionCounting
import EOC.ChordRotation
import EOC.PairValuation
import EOC.SuffixTransport
import EOC.TransportCollapse
import EOC.PrescribedMatching
import EOC.LogCorridor
import EOC.UpperEscape
import EOC.UpperCertificates
import EOC.SurvivorCounting
import EOC.CapacityBounds
import EOC.SurvivorDensity
import EOC.EntropyBounds
import EOC.SurvivorClusters
import EOC.ExceptionalPowerBound
import EOC.SplitPrefix
import EOC.LiftDigits
import EOC.ResidueDiscrepancy
import EOC.ShellWeyl
import EOC.PrefixSuffixBilinear
import EOC.PrefixCollision
import EOC.PrefixStateFormula
import EOC.ShellwiseChain
import EOC.SwapBound
import EOC.SwapCollatz
import EOC.TwistExpansion
import EOC.WeightedChain
import EOC.FirstDivergence
import EOC.BlockCube
import EOC.ShellDecomposition
import EOC.ShellRefined
import EOC.ThreeBlock
import EOC.WhiteRun
import EOC.IntervalSieve
import EOC.SpacingChain
import EOC.PsiSieve
import EOC.PsiShellBound
import EOC.PowerOrbit
import EOC.RenyiBarrier
import EOC.DecayInterface
import EOC.RenyiInstance
import EOC.GoodAngles
import EOC.TriangleArray
import EOC.BlockCubeInstance
import EOC.MaxTriangle
import EOC.TriangleHop
import EOC.WhiteContraction
import EOC.OddBlack
import EOC.LocalWindow
import EOC.DirectDescent
import EOC.LiftGap
import EOC.HarmonicFloor
import EOC.ShapeTail
import EOC.ShapeBridge
import EOC.ShapeCertificate
import EOC.BinomialEntropy
import EOC.LogAbsorb
import EOC.ShapeUnconditional
import EOC.AverageOddDark
import EOC.PressureBridge
import EOC.DangerousWindows
import EOC.ArithmeticFrontier
import EOC.Basic
import EOC.PeriodicCore
import EOC.Periodic
import EOC.BoundedDriftCore
import EOC.BoundedDrift
import EOC.FinitePrefixPacking
import EOC.HarmonicPacking
import EOC.RealizerLift
import EOC.SignedBlock
import EOC.SignedRealizer
import EOC.ChangHistory
import EOC.TaoLike.Cylinder
import EOC.TaoLike.CylinderAppend
import EOC.TaoLike.HarmonicAP
import EOC.TaoLike.ResidueTV
import EOC.TaoLike.TaoInterface
import EOC.TaoLike.ConditionalMixing
import EOC.TaoLike.PersistenceModel
import EOC.TaoLike.ShiftedPersistence
import EOC.TaoLike.EarlyLate
import EOC.TaoLike.PrefixPartition
import EOC.TaoLike.RestartLawAlignment
import EOC.TaoLike.LateShiftPersistence
import EOC.TaoLike.AllShiftsAveragedPersistence
import EOC.TaoLike.NormalizedHarmonicLaw
import EOC.TaoLike.HarmonicExceptionalSetSummability
import EOC.TaoLike.PersistenceRateCramer
import EOC.TaoLike.CylinderDigitCounting

-- Modules cited in the manuscript's formal-verification table (§14).
-- Imported here so the default build target (`lake build`) actually checks them.
import EOC.CurryFoundation
import EOC.CurryDivergenceProfile
import EOC.ChangFullShift
import EOC.ZCRERealizerGrowth
import EOC.RealizerLiftDigit
import EOC.TerminalZeroGap
import EOC.TransportRegeneration
import EOC.SuperBudgetCancellation
import EOC.ConstraintHeight
import EOC.GlobalSeparation
import EOC.OrbitLifetime
import EOC.DriftExit
import EOC.SeparatedReturns
import EOC.ZeroConfinedSeed
import EOC.CurryInterface
import EOC.PowerSavingSummable
import EOC.OscillatingEscape
