"""GATE 23 (corrected: CONFINED words only) and GATE 34 (height of the divisibility relation).

Framework.  Every realizer condition has the shape

      2^{S_N}  divides  A_N + chi * Lambda_N                                    (*)

with (A_N, Lambda_N) generated by the WORD.  The universal integer fact
"nonzero and divisible by 2^m  =>  absolute value >= 2^m" then gives

      |chi| >= (2^{S_N} - |A_N|) / |Lambda_N|,

so writing h_N := log2 max(|A_N|,|Lambda_N|) for the HEIGHT of the relation,

      log2 chi  >=  S_N - h_N - O(1).

Generic word:   (A,Lambda) = (C_N, 3^N),   h_N = alpha*N  >= S_N   ->  VACUOUS.
Periodic word:  (A,Lambda) = (c_0, Delta), h_N = O(1)             ->  log2 chi >= S_N - O(1).

So the split is  h_N/S_N -> 0  versus  h_N/S_N -> 1.
"""
import math, itertools
alpha = math.log2(3)

def v2(n):
    r=0
    while n%2==0: n//=2; r+=1
    return r

def C_of(S,N): return sum(3**(N-1-i) * (1 << S[i]) for i in range(N))
def chi_of(S,N):
    SN=S[N]; C=C_of(S,N)
    return (-C * pow(pow(3,N,1<<SN), -1, 1<<SN)) % (1<<SN)

print("GATE 23 (corrected) - positivity bound on CONFINED words")
print("  positivity says m_N >= 1, i.e. chi >= (2^{S_N} - C_N)/3^N.")
print("  Under zero confinement S_N <= floor(alpha N), so 2^{S_N} <= 2^{alpha N} = 3^N,")
print("  hence (2^{S_N} - C_N)/3^N < 1: VACUOUS (chi >= 1 is already known).")
worst = -1e9; n = 0
for N in range(4, 16):
    for c in itertools.product([1,2,3], repeat=N):
        S=[0]; ok=True
        for j,d in enumerate(c, start=1):
            S.append(S[-1]+d)
            if S[-1] > math.floor(alpha*j): ok=False; break
        if not ok: continue
        n += 1
        worst = max(worst, ((1<<S[N]) - C_of(S,N))/3**N)
        if n > 40000: break
    if n > 40000: break
print(f"  checked {n} zero-confined words; largest value of the bound = {worst:.6f}  (<1 confirms vacuity)")

print("\nGATE 34 - height h_N of the word-generated relation, by word class")
print(f"{'class':<26} {'N':>3} {'S_N':>4} {'h_N':>8} {'h_N/S_N':>8} {'floor S_N-h_N':>13} {'actual log2 chi':>16}")

def report(label, S, N, A, Lam):
    SN=S[N]; chi=chi_of(S,N)
    h = math.log2(max(abs(A), abs(Lam))) if max(abs(A),abs(Lam))>0 else 0
    lo = SN - h
    lc = math.log2(chi) if chi>0 else float('-inf')
    print(f"{label:<26} {N:>3} {SN:>4} {h:>8.2f} {h/SN:>8.4f} {lo:>13.2f} {lc:>16.2f}")

# A. periodic
for block in [(1,2),(2,1,1,2),(1,4,1,2,2)]:
    p=len(block); sigma=sum(block); reps=4; N=p*reps
    S=[0]
    for k in range(N): S.append(S[-1]+block[k%p])
    s=[0]
    for t in range(p-1): s.append(s[-1]+block[t])
    c0=sum(3**(p-1-t)*(1<<s[t]) for t in range(p)); Delta=3**p-(1<<sigma)
    report(f"periodic {block}", S, N, c0, Delta)

# D. generic / aperiodic: only (C_N, 3^N) is available
import random
random.seed(5)
for N in [12, 16, 20]:
    while True:
        S=[0]; ok=True
        for j in range(1,N+1):
            S.append(S[-1]+random.choice([1,2,3]))
            if S[-1] > math.floor(alpha*j): ok=False; break
        if ok: break
    report(f"confined irregular", S, N, C_of(S,N), 3**N)

print("\nGATE 7 redundancy check on the lattice route:")
print("  The lattice L = {(Lam,A) : A + chi*Lam = 0 mod 2^{S_N}} has det 2^{S_N},")
print("  so Minkowski always supplies a vector of height <= 2^{S_N/2}.  But (1, -chi) is")
print("  ALWAYS in L, with A + chi*Lam = 0 exactly (the degenerate branch).")
ok=0; tot=0
for N in [8,10,12]:
    for _ in range(200):
        S=[0]; good=True
        for j in range(1,N+1):
            S.append(S[-1]+random.choice([1,2,3]))
            if S[-1] > math.floor(alpha*j): good=False; break
        if not good: continue
        tot+=1
        chi=chi_of(S,N)
        if (( -chi) + chi*1) % (1<<S[N]) == 0: ok+=1
print(f"  (1,-chi) lies in L and is degenerate: {ok}/{tot} confined words -> the short vector")
print("  is generated by chi itself, so the lattice bound is CIRCULAR, not a second constraint.")
